dbtlearn:
  outputs:
    dev:
      account: ppujnvu-ux92473
      database: AIRBNB
      password: dbtPassword123
      role: TRANSFORM
      schema: DEV
      threads: 1
      type: snowflake
      user: dbt
      warehouse: COMPUTE_WH
  target: dev
